name: Sample workflow

on:
  push:
    branches:
      - master

env:
  value: Ravishankar

jobs:
  MyFirstJob:
    name: myfirstJob
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: step1
        run: |
          echo ${{ env.value }}

      
