
name: Sample Workflow

on: 
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: command
        run: echo "This is my first github action workflow"
      
