name: workflowOn Call

on:
  workflow_call:
    outputs:
      mainOut: 
        value: ${{ jobs.sampleJObs2.outputs.outName }}
      mainAge:
        value: ${{ jobs.sampleJObs2.outputs.outAge }}
    inputs:
      value1:
        description: This is used to print the value
        type: string
        required: true
      value2:
        description: This is used to print value2
        type: number
        required: true
      value3:
        description: This is used to print value3
        type: boolean
        default: false
        required: false

jobs:
  sampleJob:
    if: ${{ inputs.value3 }}
    runs-on: ubuntu-latest
    steps:
      - name: OnlyRun
        run: |
          echo "Runs only when value3 is ${{ inputs.value3 }}"
  
  sampleJObs2:
    runs-on: ubuntu-latest
    outputs:
      outName: ${{ steps.onlyRun.outputs.name }}
      outAge: ${{ steps.onlyRun.outputs.age }}
    steps:
      - name: OnlyRun
        id: onlyRun
        run: |
          echo "name=${{ inputs.value1 }}" >> $GITHUB_OUTPUT
          echo "age=${{ inputs.value2 }}" >> $GITHUB_OUTPUT
      
